name: build

on:
  push:
    branches:
      - '**'
  create:
    branches:
      - 'master'
    tags:
      - '**'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        eval "$(conda shell.bash hook)"
        conda activate base
        pip install -U https://api.github.com/repos/benchopt/benchOpt/zipball/CLN_remove_benchmarks
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
    - name: Test
      run: |
        eval "$(conda shell.bash hook)"
        conda activate base
        pip --version
        which benchopt
        pip freeze | grep benchopt
        conda env list
        benchopt test . --env-name benchopt_ols_test_env -vl
        benchopt test . --env-name benchopt_ols_test_env -vl --skip-install
